### PR TITLE
Update to WebSDK2.3

### PR DESCRIPTION
**Pull request by echolabstech**

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks . May I ask you to submit this change directly to the cas project itself?

**Comment by echolabstech** [comment]
Sure

**Comment by echolabstech** [comment]
I need access though

**Comment by mmoayyed** [comment]
Not sure I follow. Wouldn't you be able to submit the same change set to http://github.com/apereo/cas? Duo is supported by cas natively now.

**Comment by echolabstech** [comment]
I was about to make a pull request on the cas project itself, until I came across this:
`- [] I have signed the Apereo ICLA form, located here: https://www.apereo.org/licensing/agreements/icla
`
Do you really need me to sign this?

**Comment by mmoayyed** [comment]
No we should fix that. That is optional.

**Comment by mmoayyed** [comment]
Removed that clause

**Comment by echolabstech** [comment]
Cool. [Requested](https://github.com/apereo/cas/pull/1951).

**Pull request closed without merging**
