### PR TITLE
Duo Web MFA V2

### PR DESCRIPTION
**Pull request by mschwager**
We've created a new version of the Duo Web library. Some of the new features include:

* CSP compliant (https://en.wikipedia.org/wiki/Content_Security_Policy)
* The frame plays better with different size screens now
* No external dependencies (no jquery, or postmessage required)
* Much smaller

### CODE REVIEW

**Comment by mmoayyed** [comment]
Pardon me for asking, who is "we" in this context?

**Comment by mschwager** [comment]
We is Duo, I'm a developer there. You can confirm the JS files are correct by comparing them with

https://api.duosecurity.com/frame/hosted/Duo-Web-v2.js
https://api.duosecurity.com/frame/hosted/Duo-Web-v2.min.js

**Comment by mmoayyed** [comment]
Ah, excellent. Thanks. 

Just FYI, this extension will soon go away as the CAS project itself is planning to support duo directly:
https://github.com/Jasig/cas/tree/master/cas-server-support-duo

I'll take your patch and apply it there directly. But if you are planning to submit more PRs, you should directly get them to CAS if possible

Thanks again.

P.S: Any chance your Java API could find its way into Maven central? We have asked this question many times, I know :), but we have yet to receive a response.

**Comment by mmoayyed** [comment]
by the way, would it make sense to have CAS directly load JS files from Duo? Long-term maintenance, wouldnt that be easier rather than hosting files directly in the project?

**Comment by mschwager** [comment]
Awesome, thanks for the heads up!

Regarding the Maven packages, we would really like to make this happen, but it's difficult to find the time, especially since I know next to nothing about Java development :)

As for pointing to the Duo hosted JS files, we typically encourage websites to host the files for security purposes.

**Comment by mmoayyed** [comment]
Very well. Thanks for the tip. 

Since you're contributing to CAS, I'd be remiss if I didnt offer a hand to help with the Java side of things. I'd be more than happy to release duo for you if you need extra time/help. The first pre-req would for someone like me to have push access to the repo so we could start with the release. How could I go about that, if that offer appeals to you guys? :)

**Pull request merged**
